name: Github Pages Deploy

on:
  push:
    branches:
      - "main"

env:
  REGISTRY: ghcr.io
  FRONTEND_TAG_PUSH: ghcr.io/piet2001/sportscentre-frontend:${{ github.sha }}      

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build
        run: npm install && npm run build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.  ''

      - name: Build & push  
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.FRONTEND_TAG_PUSH }}